### PR TITLE
[MRG] clarify importance of findMethod arg in README

### PR DESCRIPTION
**Pull request by rythorpe**

### CODE REVIEW

**Comment by rythorpe** [comment]
@stephanie-r-jones WDYT of this?

**Comment by stephanie-r-jones** [comment]
Hi Ryan, 

One thing that I find confusing here is that FindMethod is defined as inputs in both spectralevents and spectralevents_find but I don't see it as input in the spectralevents_find function? Should it be there? IF not, we should move the description up to be under "spectralevents" function. Also I think it would help to add the world "FindMethods"  to the top of description right before "Algorithms for finding and calculating..."

**Comment by rythorpe** [comment]
> One thing that I find confusing here is that FindMethod is defined as inputs in both spectralevents and spectralevents_find but I don't see it as input in the spectralevents_find function? Should it be there? IF not, we should move the description up to be under "spectralevents" function. Also I think it would help to add the world "FindMethods" to the top of description right before "Algorithms for finding and calculating..."

Oops, that's a typo! `findMethod` is indeed defined in `spectralevents_find`. I'll fix that too...

**Comment by rythorpe** [comment]
@stephanie-r-jones I'm going to go ahead and merge this. Feel free to open a new issue or we can discuss this further in our next meeting if there are additional changes you want made.

**Comment by stephanie-r-jones** [comment]
👍

**Pull request merged**
