### PR TITLE
Python code for Spectral Events detection and characterising added

### PR DESCRIPTION
**Pull request by tbardouille**
Hi there,

I've translated your code into Python so that I (and others) can use it for MEG data analysis in that environment. The python code generates comparable results to your Matlab code (see test_results folder). 

Functionally, the only major change is in local maxima detection, since I used a different function for this (I couldn't find a python equivalent of the Matlab function that you used). In the python function, the footprint of the maxima detector can be tuned. I used a footprint that seems to eliminate Matlab's behaviour of giving multiple maxima for one peak (see results).  

Hopefully, this will be helpful to other MEG/EEG/LFP'ers!

Best regards,
Tim.

### CODE REVIEW

**Comment by rythorpe** [comment]
Hi Tim, this is really great - I'm excited about adding python functionality. This is minor, but how did you decide on the values assigned to the maximum_filter neighborhood size? I know Matlab's imregionalmax function defines its default 2D neighborhood as the 8 surrounding values in a square grid, but I don't follow how you assigned this in your python version.

**Comment by tbardouille** [comment]
Hi Ryan,

I didn't realize that imregionalmax had a setting for that. You can see lines 44-47 in test.py for the settings that I chose. I set the footprint to be 8 in frequency and 40 in time. I used a longer setting in time to avoid getting multiple events for the same local peak, based on some other TFR work that I have done. You're probably correct that this makes a minor difference. Perhaps this should be set to 8 in frequency and 8 in time, then? Or should we just make it more clear that this is a tuneable parameter?

Also, should I add a file that indicates the versions of python (and dependencies) that I'm using?

Tim.

**Comment by rythorpe** [comment]
@tbardouille yes, there are certainly going to be minor differences with your current implementation of retrieving maxima so we just need to specify this in the documentation. The values of 8 in frequency and 40 in time correspond to index values instead of time/frequency units right?

While it might be interesting to allow the maxima footprint to be a tunable parameter, my original goal with this toolbox was to provide a handful of stand-alone functions that accommodate a clear definition of "spectral events". (This is also why we ended up veering away from an object-oriented toolbox that, while sacrificing out-of-box simplicity, allows those with less coding experience to use individual script files as needed.)  By highlighting arbitrary maxima filter footprint sizing, spectral event definition becomes more ambiguous, which I think we should avoid. In the Matlab functions, all 3 event-finding methods start by finding all relative maxima in a suprathreshold TFR region given any resolution in time-frequency space. Each event-finding method then differentiates how those maxima are accepted or rejected, allowing the user clearly define the number and location of the "spectral events" within any given suprathreshold region. All that said, I think your method for calculating center-of-mass within each region makes way more sense than just finding the spatial center in a square grid of time-frequency space (which is what the Matlab version currently does). Let's definitely discuss this further!

Yes, python version and dependencies would be great. Maybe we can also include a python env file to ensure reproducibility.

**Comment by tbardouille** [comment]
@rythorpe , I just found a small bug in the code thank to one of my graduate students. The FWHM for frequency is reported in index number rather than Hz. This doesn't matter for the test case where fstep=1, but will be problematic if fstep != 1. I will send a fix by tomorrow (I have to go be a parent right now).

By the way, are you at OHBM? It would be great to discuss in person with you.

**Comment by rythorpe** [comment]
@tbardouille No worries, I'm glad you guys caught that - I've made that mistake a few times as well. I'm at Brown University, but let's definitely find a way to discuss this in more detail. How about we schedule a Zoom meeting?

**Pull request merged**
